### ISSUE TITLE
Understand and document our Next.js 15 support

### ISSUE THREAD

**Issue by dario-piotrowicz** [opennextjs/opennextjs-cloudflare#165]
We should investigate, fully understand and document our adapter support for Next.js 15, to what extent we support this version of Next.js and what feature of it we support and which we don't

> [!Note]
> This for our currently experimental prerelease package

**Comment by dario-piotrowicz** [comment]
@vicb I think you should already have a pretty good idea of the support for Next.js 15, but I don't think you have a 100% clear idea of the extent of our support for it, or do you?

Please feel free to add to the issue any extra context you have 🙂

**Comment by vicb** [comment]
The Next (15 or earlier) is a valid question.

I think we have issues for all the known gaps.

The first "TODO" issue on [the project board](https://github.com/orgs/opennextjs/projects/1/views/2) is about adding more tests which should give us a better understand about where we stand.

As this issue is not actionable and has no good definition of done, you should consider moving it to a discussion.

**Comment by dario-piotrowicz** [comment]
> As this issue is not actionable and has no good definition of done, you should consider moving it to a discussion.

I'm not sure how this is not actionable and doesn't have a good definition of done 😕 (definition of done === [our supported doc](https://opennext.js.org/cloudflare#supported-nextjs-features) is updated with Next.js 15 and all its features)

Anyways if you find this issue not valuable for tracking purposes please feel free to close it, no hard feelings 🙂

**Comment by vicb** [comment]
Maybe we can use #108 (investigation) and #159 (docs) adding specific points there?

**Comment by dario-piotrowicz** [comment]
Ok, I've added comments there 🙂

Thanks 👍
