### ISSUE TITLE
Investigate the blog example

### ISSUE THREAD

**Issue by vicb** [opennextjs/opennextjs-cloudflare#174]
The blog is failing because it try to access to filesystem.

Need to investigate and fix.

**Comment by conico974** [comment]
This is likely coming from here https://github.com/opennextjs/opennextjs-cloudflare/blob/main/examples/vercel-blog-starter/src/lib/api.ts

**Comment by james-elicx** [comment]
I believe this is because there is no cache handler serving the seed files anymore so it's falling back to on-demand ISR for the routes when they should be SSG'd at build time. Part of the reason I added the [seed file stuff](https://github.com/opennextjs/opennextjs-cloudflare/blob/main/packages/cloudflare/src/cli/templates/cache-handler/open-next-cache-handler.ts#L48) in the cache handler in main was because I had the same problem with my blog.

**Comment by vicb** [comment]
Thanks @conico974 and @james-elicx.

I think re-introducing cache would solve that, we can hopefully come to that this week.
