### ISSUE TITLE
`ERR_PNPM_NO_SCRIPT  Missing script: cloudflare`

### ISSUE THREAD

**Issue by kylehotchkiss** [opennextjs/opennextjs-cloudflare#40]
Followed installation instructions for Cloudflare per the readme:

`pnpm add -D wrangler@latest @opennextjs/cloudflare`

`pnpx cloudflare` results in `ERR_PNPM_NO_SCRIPT  Missing script: cloudflare`

I can verify that both the `@opennextjs/cloudflare` folder is present in `node_modules` and cloudflare is not in `node_modules/.bin`

Node v20
pnpm v9.1.0

Thank you all for your hard work on this, can't wait to run more sites on Cloudflare :)

**Comment by dario-piotrowicz** [comment]
Hi @kylehotchkiss 🙂 

Instead of running
```
pnpx cloudflare
```
I think you should run
```
pnpm exec cloudflare
```

that's because `pnpx` is an alias to [`pnpm dlx`](https://pnpm.io/cli/dlx) which fetches and runs a package from the registry (in your case it tries to fetch and run the `cloudflare` package).

[`pnpm exec`](https://pnpm.io/cli/exec) does instead execute commands of dependencies, which here is indeed what we want.

What do you think? 🙂

**Comment by dario-piotrowicz** [comment]
@kylehotchkiss thanks for confirming 😄 

Yeah I think that the command we've got in the package readme are incorrect, I am ammending that in #48 😄👍
